apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ingress-cert
  namespace: argocd
spec:
  secretName: argocd-ingress-cert
  commonName: argo.aks.diehlabs.com
  dnsNames:
  - argo.aks.diehlabs.com
