apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argo-issuer
  namespace: argocd
spec:
  acme:
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: 502ac5b9-6b22-453d-94f9-5eee652d01ac
          resourceGroupName: diehlabs-dns-nonprod
          hostedZoneName: aksnp.diehlabs.com
          # managedIdentity:
          #   clientID: 69822f8c-f3b1-4bc4-bf82-00aa51bb6ca5
