apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../../base

# components:
# - https://github.com/argoproj-labs/argocd-extensions/manifests

patchesStrategicMerge:
- applications.yaml
- certificate.yaml
- gateway.yaml
# - issuer.yaml
- rollouts-extension.yaml
- virtualservice.yaml

patchesJson6902:
- path: issuer-patch.yaml
  target:
    group: cert-manager.io
    kind: Issuer
    name: argo-issuer
    version: v1

# images:
# - name: quay.io/argoproj/argocd
#   newName: ghcr.io/argoproj/argocd
#   newTag: 2.5.0-9fac0f6a
