apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# DO NOT SPECIFY NAMESPACE
# It will replace the namespace on things like roles which need to be left instact
# namespace: cert-manager

resources:
- https://github.com/kubereboot/kured/releases/download/1.10.2/kured-1.10.2-dockerhub.yaml
