apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
  namespace: argocd
spec:
  source:
    targetRevision: '1.54.0'
# check istio-kiali version compatibility
# https://kiali.io/docs/installation/installation-guide/prerequisites/