apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: argocd

resources:
- ../../base

patchesStrategicMerge:
- argo-cd.yaml
- argo-rollouts.yaml
- azure-workload-identity.yaml
- cert-manager.yaml
- external-dns.yaml
- istio.yaml
- kiali.yaml
# - vault.yaml
