apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesJson6902:
- path: azure-dns.yaml
  target:
    group: apps
    kind: Deployment
    name: external-dns
    version: v1
