apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# DO NOT SPECIFY NAMESPACE
# It will replace the namespace on things like roles which need to be left instact
# namespace: cert-manager

resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml
- cluster-issuer.yaml
  