# The cluster issuer requires a k8s secret for the spn client secret
# create ahead of time for now, later use vault
# apiVersion: v1
# kind: Secret
# metadata:
#   name: azuredns-config
#   namespace: cert-manager
# type: Opaque
# data:
#   client-secret: <base64 encoded spn client secret>
# ---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer # can be namespace specific using Issuer or "global" using ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    solvers:
      - dns01:
          azureDNS:
            tenantID: fc6ff48d-9858-46be-be10-c3a663f4bcbf
