apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# DO NOT SPECIFY NAMESPACE
# It will replace the namespace on things like roles which need to be left instact
# namespace: cert-manager

resources:
- ../../base

# patchesStrategicMerge:
# - cluster-issuer.yaml

patchesJson6902:
- path: azure-dns.yaml
  target:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
    version: v1

# secretGenerator:
# - name: azuredns-config
#   envs:
#   - config.properties
