apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.3/manifests/ha/install.yaml
- applications.yaml
- certificate.yaml
- gateway.yaml
- issuer.yaml
- virtualservice.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests

patchesJson6902:
- path: argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1
