apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-rollouts.yaml
- azure-workload-identity.yaml
- istio.yaml
# dns will create records for istio gateways and vs
- external-dns.yaml
# certs will be created for fqdns of gateways
- cert-manager.yaml
# these will create their own istio gateways
- argo-cd.yaml
- kiali-operator.yaml
- kiali-server.yaml
- kured.yaml
- vault.yaml